### PR TITLE
Chapter12

### PR DESCRIPTION
**Pull request by waltergomero**

### CODE REVIEW

**Comment by JonPSmith** [comment]
Hi @waltergomero,

I don't know if you meant to do this pull request, but this repository doesn't work like that. The master fork is empty and each chapter has its own branch - see the [README.md file](https://github.com/JonPSmith/EfCoreInAction/blob/master/README.md).

I have done this because it makes each chapter separate, but linked to the last chapter. This is very helpful as the data inside the example book setting site changes at the chapters progress. It also means I can update one chapter and then feed it up to the other chapters - that is how I am converting the whole of the code over to .NET Core 2.

Hope that helps.

**Comment by waltergomero** [comment]
Hi sir,
I download a zip copy of each chapters sir.

Regards,
Walter

**Comment by JonPSmith** [comment]
Hi @waltergomero,

Be warned. I'm in the middle of updating the repostory to .NET Core 2. If you took copies ysterday then chapter 1 to 5 are using .NET Core 2, while the other chapters are using .NET Core 1.1

**Comment by waltergomero** [comment]
Thank you for the updates sir. 
Regards Walter


Sent from my Sprint Samsung Galaxy S7.
-------- Original message --------From: Jon P Smith <notifications@github.com> Date: 8/26/17  11:39 AM  (GMT-06:00) To: JonPSmith/EfCoreInAction <EfCoreInAction@noreply.github.com> Cc: waltergomero <walter.gomero@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [JonPSmith/EfCoreInAction] Chapter12 (#1) 
Hi @waltergomero,
Be warned. I'm in the middle of updating the repostory to .NET Core 2. If you took copies ysterday then chapter 1 to 5 are using .NET Core 2, while the other chapters are using .NET Core 1.1

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/JonPSmith/EfCoreInAction","title":"JonPSmith/EfCoreInAction","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/JonPSmith/EfCoreInAction"}},"updates":{"snippets":[{"icon":"PERSON","message":"@JonPSmith in #1: Hi @waltergomero,\r\n\r\nBe warned. I'm in the middle of updating the repostory to .NET Core 2. If you took copies ysterday then chapter 1 to 5 are using .NET Core 2, while the other chapters are using .NET Core 1.1"}],"action":{"name":"View Pull Request","url":"https://github.com/JonPSmith/EfCoreInAction/pull/1#issuecomment-325145018"}}}

**Pull request closed without merging**
